In [1]:
import json ,os

In [4]:
fls = os.listdir('data/ObliQADataset/StructuredRegulatoryDocuments')

In [ ]:
indx = {}
for f in fls:
	file = json.load(open('data/ObliQADataset/StructuredRegulatoryDocuments/'+f))
	c = f[:-5]
	

In [5]:
test = json.load(open('/home/ubuntu/projects/regnlp/data/ObliQADataset/ObliQA_test.json'))
dc = {}
for q in test:
	dc[len(q['Passages'])] = dc.get(len(q['Passages']),0) + 1

In [6]:
dc

{1: 2126, 2: 506, 4: 36, 3: 105, 6: 4, 5: 9}

In [7]:
import pandas as pd 

In [8]:
pd.DataFrame({'a':[1,2], 'b':[3,2]})

a  b
0  1  3
1  2  2

In [19]:
c, corpus, idx = 0, {}, {}
print('Building Corpus ...')
for i in range(1,41):
	file = json.load(open('/home/ubuntu/projects/regnlp/data/ObliQADataset/StructuredRegulatoryDocuments/'+f'{i}.json'))
	for p in file:
		did, pid = p['DocumentID'] ,p['PassageID']
		if f'{did}_{pid}' in idx: print(f'{did}_{pid}')
		idx[f'{did}_{pid}'] = c
		corpus[c] = {'id':c, 'doc':did, 'psg':pid, 'txt':p['Passage']}
		c+=1


Building Corpus ...


In [20]:
json.dump(corpus, open('/home/ubuntu/projects/regnlp/data/ObliQADataset/corpus.json','w'))

In [18]:
with open('/home/ubuntu/projects/regnlp/data/ObliQADataset/corpus.txt','w') as fh:
	for l in corpus:
		fh.write(f'{l}\n')

In [21]:
revidx = {v:k for k,v in idx.items()}

In [22]:
json.dump(revidx, open('/home/ubuntu/projects/regnlp/data/ObliQADataset/index.json','w'))

In [12]:
dbls = {}
for k in idx:
	if k.count('_') >= 2 and k[-2]=='_' and k[-1] in '1234567':
		did, pid, vid = k.split('_')
		dbls[f'{did}_{pid}'] = dbls.get(f'{did}_{pid}',[f'{did}_{pid}']) + [k]

for k in dbls:
	vs = dbls[k]
	file = json.load(open('/home/ubuntu/projects/regnlp/data/ObliQADataset/StructuredRegulatoryDocuments/'+f'{k.split("_")[0]}.json'))
	pss = [{'id':v, 'txt':p['Passage']} for v in vs for p in file if p['PassageID']=='_'.join(v.split('_')[1:])]
	dbls[k] = pss




In [13]:
dbls

{'7_3.3.40.Guidance': [{'id': '7_3.3.40.Guidance', 'txt': ''},
  {'id': '7_3.3.40.Guidance_1',
   'txt': 'An Authorised Person should observe best practices when establishing the systems and controls required under Rule 3.3.38, given the evolving nature of Financial Crime. Such practices may include, but are not limited to, incorporating secure authentication, biometrics and the monitoring of customer behaviour metrics into anti-fraud and anti-Financial Crime systems and controls.\n\n'}],
 '7_1.': [{'id': '7_1.', 'txt': 'INTRODUCTION\n'},
  {'id': '7_1._1',
   'txt': 'Corporate governance is a framework of systems, policies, procedures and controls through which an entity:\na.\tpromotes the sound and prudent management of its business;\nb.\tprotects the interests of its Customers and stakeholders; and\nc.\tplaces clear responsibility for achieving Rule \u200e3.3.41(2)(a) and \u200e(3) on the Governing Body and its members and the senior management of the Authorised Person.\n'}],
 '7_5.

In [16]:
cc =0
for name in ['dev', 'test', 'train']:
	file = json.load(open(f'/home/ubuntu/projects/regnlp/data/ObliQADataset/ObliQA_{name}.json'))
	for i,q in enumerate(file):
		for j,p in enumerate(q['Passages']):
			if f'{p["DocumentID"]}_{p["PassageID"]}' in dbls:
				fnd = False
				for d in dbls[f'{p["DocumentID"]}_{p["PassageID"]}']:
					if d['txt'] == p['Passage']:
						fnd = True 
						file[i]['Passages'][j]['PassageID'] = d['id']
						cc +=1
						break
				if not fnd : print(f'not found for {name}, {q}, {p}')

	json.dump(file, open(f'/home/ubuntu/projects/regnlp/data/ObliQADataset/splits/ObliQA_{name}.json','w'))

In [24]:
for name in ['dev', 'test', 'train']:
	file = json.load(open(f'/home/ubuntu/projects/regnlp/data/ObliQADataset/splits/ObliQA_{name}.json'))
	out = []
	for q in file:
		#ky = f'{q["DocumentID"]}_{q["PassageID"]}'
		refs = [idx[f'{p["DocumentID"]}_{p["PassageID"]}'] for p in q["Passages"]]
		out.append({'query':q['Question'], 'pos':refs})
	json.dump(out, open(f'/home/ubuntu/projects/regnlp/data/ObliQADataset/splits/{name}.json','w'))


In [8]:
revidx[482]

'1_14.2.3.Guidance.10.'

In [15]:
len(corpus)

13732

In [2]:
corpus = json.load(open('/home/ubuntu/projects/regnlp/data/ObliQADataset/corpus.json'))

In [5]:
for k,v in corpus.items():
	nm = f'{v["doc"]}_{v["psg"]}'
	nm = nm.split('/')[0]
	with open(f'/home/ubuntu/projects/regnlp/data/ObliQADataset/txt/{nm}.txt','w') as fh:
		fh.write(v["txt"])

In [6]:
indx = json.load(open('/home/ubuntu/projects/regnlp/data/ObliQADataset/new/index.json'))

In [7]:
revidx = {v:k for k,v in indx.items()}

In [12]:
list(revidx.keys())[:10]

['1_1.',
 '1_1.1',
 '1_1.1.1',
 '1_1.1.1.(1)',
 '1_1.1.1.(2)',
 '1_1.2',
 '1_1.2.1',
 '1_1.2.1.(1)',
 '1_1.2.1.(2)',
 '1_1.2.1.Guidance']

In [10]:
revidx['1']

KeyError: '1'

In [13]:
indx['482']

'1_14.2.3.Guidance.10.'

In [18]:
import math
import numpy as np

class BM25:
    def __init__(self, corpus, tokenizer=None):
        self.corpus_size = 0
        self.avgdl = 0
        self.doc_freqs = []
        self.idf = {}
        self.doc_len = []
        self.tokenizer = tokenizer


        nd = self._initialize(corpus)
        print(nd)
        self._calc_idf(nd)

    def _initialize(self, corpus):
        nd = {}  # word -> number of documents with word
        num_doc = 0
        for document in corpus:
            self.doc_len.append(len(document))
            num_doc += len(document)

            frequencies = {}
            for word in document:
                if word not in frequencies:
                    frequencies[word] = 0
                frequencies[word] += 1
            self.doc_freqs.append(frequencies)

            for word, freq in frequencies.items():
                try:
                    nd[word]+=1
                except KeyError:
                    nd[word] = 1

            self.corpus_size += 1

        self.avgdl = num_doc / self.corpus_size
        return nd


class BM25Okapi(BM25):
    def __init__(self, corpus, tokenizer=None, k1=1.5, b=0.75, epsilon=0.25):
        self.k1 = k1
        self.b = b
        self.epsilon = epsilon
        super().__init__(corpus, tokenizer)

    def _calc_idf(self, nd):
        """
        Calculates frequencies of terms in documents and in corpus.
        This algorithm sets a floor on the idf values to eps * average_idf
        """
        # collect idf sum to calculate an average idf for epsilon value
        idf_sum = 0
        # collect words with negative idf to set them a special epsilon value.
        # idf can be negative if word is contained in more than half of documents
        negative_idfs = []
        for word, freq in nd.items():
            idf = math.log(self.corpus_size - freq + 0.5) - math.log(freq + 0.5)
            self.idf[word] = idf
            idf_sum += idf
            if idf < 0:
                negative_idfs.append(word)
        self.average_idf = idf_sum / len(self.idf)

        eps = self.epsilon * self.average_idf
        for word in negative_idfs:
            self.idf[word] = eps

    def get_scores(self, query):
        """
        The ATIRE BM25 variant uses an idf function which uses a log(idf) score. To prevent negative idf scores,
        this algorithm also adds a floor to the idf value of epsilon.
        See [Trotman, A., X. Jia, M. Crane, Towards an Efficient and Effective Search Engine] for more info
        :param query:
        :return:
        """
        score = np.zeros(self.corpus_size)
        doc_len = np.array(self.doc_len)
        for q in query:
            q_freq = np.array([(doc.get(q) or 0) for doc in self.doc_freqs])
            score += (self.idf.get(q) or 0) * (q_freq * (self.k1 + 1) /
                                               (q_freq + self.k1 * (1 - self.b + self.b * doc_len / self.avgdl)))
        return score

In [2]:
corpusss = [

	"i saw a cat",
	"lion is the best animal",
	"cat and dog are animal",
	"i have the best dog",
	"dog dog"
]

corpus = [c.split() for c in corpusss]

In [3]:
corpus_size = 0
avgdl = 0
doc_freqs = []
idf = {}
doc_len = []
nd = {}  # word -> number of documents with word
num_doc = 0
for document in corpus:
	doc_len.append(len(document))
	num_doc += len(document)

	frequencies = {}
	for word in document:
		if word not in frequencies:
			frequencies[word] = 0
		frequencies[word] += 1
	doc_freqs.append(frequencies)

	for word, freq in frequencies.items():
		try:
			nd[word]+=1
		except KeyError:
			nd[word] = 1

	corpus_size += 1

avgdl = num_doc / corpus_size


In [29]:
import math
idff_sum = 0
epsilon = .25
# collect words with negative idf to set them a special epsilon value.
# idf can be negative if word is contained in more than half of documents
negative_idfs = []
for word, freq in nd.items():
	idff = math.log(corpus_size - freq + 0.5) - math.log(freq + 0.5)
	idf[word] = idff
	idff_sum += idff
	if idff < 0:
		negative_idfs.append(word)
average_idf = idff_sum / len(idf)

eps = epsilon * average_idf
for word in negative_idfs:
	idf[word] = eps

In [4]:
doc_freqs

[{'i': 1, 'saw': 1, 'a': 1, 'cat': 1},
 {'lion': 1, 'is': 1, 'the': 1, 'best': 1, 'animal': 1},
 {'cat': 1, 'and': 1, 'dog': 1, 'are': 1, 'animal': 1},
 {'i': 1, 'have': 1, 'the': 1, 'best': 1, 'dog': 1},
 {'dog': 2}]

In [31]:
nd

{'i': 2,
 'saw': 1,
 'a': 1,
 'cat': 2,
 'lion': 1,
 'is': 1,
 'the': 2,
 'best': 2,
 'animal': 2,
 'and': 1,
 'dog': 3,
 'are': 1,
 'have': 1}

In [5]:
voc = list(nd.keys())
tok2idx = {voc[i]:i for i in range(len(voc))}
idx2tok = {i:voc[i] for i in range(len(voc))}

In [6]:
enc_corp = [[tok2idx[t] for t in c] for c in corpus]

In [7]:
enc_corp

[[0, 1, 2, 3], [4, 5, 6, 7, 8], [3, 9, 10, 11, 8], [0, 12, 6, 7, 10], [10, 10]]

In [38]:
docs = []
for d in doc_freqs:
	denc = [0]*13
	for k,v in d.items():
		denc[tok2idx[k]] = v
	docs.append(denc)

In [39]:
docs

[[1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0],
 [0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0],
 [1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0]]

In [30]:
idf

{'i': 0.33647223662121295,
 'saw': 1.0986122886681098,
 'a': 1.0986122886681098,
 'cat': 0.33647223662121295,
 'lion': 1.0986122886681098,
 'is': 1.0986122886681098,
 'the': 0.33647223662121295,
 'best': 0.33647223662121295,
 'animal': 0.33647223662121295,
 'and': 1.0986122886681098,
 'dog': 0.17377259552233887,
 'are': 1.0986122886681098,
 'have': 1.0986122886681098}

In [40]:
idfvec = [0]*13
for k,v in idf.items():
	idfvec[tok2idx[k]] = v
idfvec

[0.33647223662121295,
 1.0986122886681098,
 1.0986122886681098,
 0.33647223662121295,
 1.0986122886681098,
 1.0986122886681098,
 0.33647223662121295,
 0.33647223662121295,
 0.33647223662121295,
 1.0986122886681098,
 0.17377259552233887,
 1.0986122886681098,
 1.0986122886681098]

In [32]:
import numpy as np
k1, b = 1.5, .5
query = ["i", "have", "cat", "cat"]
score = np.zeros(corpus_size)
doc_len = np.array(doc_len)
for q in query:
	q_freq = np.array([(doc.get(q) or 0) for doc in doc_freqs])
	score += (idf.get(q) or 0) * (q_freq * (k1 + 1) /
										(q_freq + k1 * (1 - b + b * doc_len / avgdl)))

In [33]:
score

array([1.02404594, 0.        , 0.6365691 , 1.35751239, 0.        ])

In [ ]:
tensor([1.0240, 0.0000, 0.6366, 1.3575, 0.0000])

In [64]:
qvec = [0]*13
for q in query:
	qvec[tok2idx[q]] +=1
qvec

[1, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1]

In [43]:
avgdl

4.2

In [42]:
docs = torch.tensor(docs)

In [44]:
doc_len = docs.sum(1, keepdim=True).repeat(1,docs.shape[-1]) /avgdl

In [45]:
doc_len

tensor([[0.9524, 0.9524, 0.9524, 0.9524, 0.9524, 0.9524, 0.9524, 0.9524, 0.9524,
         0.9524, 0.9524, 0.9524, 0.9524],
        [1.1905, 1.1905, 1.1905, 1.1905, 1.1905, 1.1905, 1.1905, 1.1905, 1.1905,
         1.1905, 1.1905, 1.1905, 1.1905],
        [1.1905, 1.1905, 1.1905, 1.1905, 1.1905, 1.1905, 1.1905, 1.1905, 1.1905,
         1.1905, 1.1905, 1.1905, 1.1905],
        [1.1905, 1.1905, 1.1905, 1.1905, 1.1905, 1.1905, 1.1905, 1.1905, 1.1905,
         1.1905, 1.1905, 1.1905, 1.1905],
        [0.4762, 0.4762, 0.4762, 0.4762, 0.4762, 0.4762, 0.4762, 0.4762, 0.4762,
         0.4762, 0.4762, 0.4762, 0.4762]])

In [48]:
idfvec = torch.tensor(idfvec)
denom = (docs + k1 *(1 - b + b * doc_len))
nom = idfvec * ((k1 + 1) * docs )

In [49]:
#doc_len = docs.sum(1, keepdim=True).repeat(1,docs.shape[-1]) /avgdl
docs_idf =  nom/denom 


In [62]:
docs_idf

tensor([[0.3413, 1.1145, 1.1145, 0.3413, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 1.0392, 1.0392, 0.3183, 0.3183, 0.3183,
         0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.3183, 0.0000, 0.0000, 0.0000, 0.0000, 0.3183,
         1.0392, 0.1644, 1.0392, 0.0000],
        [0.3183, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.3183, 0.3183, 0.0000,
         0.0000, 0.1644, 0.0000, 1.0392],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.2796, 0.0000, 0.0000]])

In [65]:
qt = torch.tensor(qvec, dtype=torch.float)


In [63]:
qvec

tensor([1., 0., 0., 2., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       dtype=torch.float64)

In [66]:
import torch 
scores = torch.matmul(docs_idf, qt)

In [67]:
scores

tensor([1.0240, 0.0000, 0.6366, 1.3575, 0.0000])

In [ ]:
[0.30757724, 0.30757724, 0.21342094, 0.41830505, 0.24320061,
       3.31848878, 0.28263855, 1.32300047, 0.        , 0.45967588]

In [19]:
bm25 = BM25Okapi(cpr_tok)

{'cat': 7, 'saw': 3, 'the': 5, 'dog': 7, 'and': 3, 'are': 2, 'more': 1, 'than': 1, 'i': 2, 'a': 1, 'lion': 3, 'is': 1, 'best': 2, 'animal': 2, 'have': 1, 'ate': 1}


In [17]:
bm25.idf

{'cat': 0.2614406550238335,
 'saw': 0.7621400520468966,
 'the': 0.0,
 'dog': 0.2614406550238335,
 'and': 0.7621400520468966,
 'are': 1.2237754316221157,
 'more': 1.845826690498331,
 'than': 1.845826690498331,
 'i': 1.2237754316221157,
 'a': 1.845826690498331,
 'lion': 0.7621400520468966,
 'is': 1.845826690498331,
 'best': 1.2237754316221157,
 'animal': 1.2237754316221157,
 'have': 1.845826690498331,
 'ate': 1.845826690498331}

In [21]:
bm25.get_scores(["what", "is", "the", "best", "cat"])

array([0.30757724, 0.30757724, 0.21342094, 0.41830505, 0.24320061,
       3.31848878, 0.28263855, 1.32300047, 0.        , 0.45967588])

In [23]:
bm25.get_scores(cpr_tok[0])

array([1.51178984, 1.51178984, 0.60074043, 0.41830505, 0.9521681 ,
       0.        , 0.56527709, 0.28263855, 0.30757724, 0.91935175])

In [24]:
bm25.get_scores(["best", "animal", "is", "more", "than", "a", "animal"])

array([0.        , 0.        , 3.0135946 , 0.        , 2.50281585,
       5.96448971, 2.64600093, 1.32300047, 0.        , 0.        ])

In [30]:
bm25.get_scores(['cat', 'saw', 'the', 'dog', "saw", "saw", "saw", "saw", "saw", "saw"])

array([6.89160197, 6.89160197, 0.60074043, 0.41830505, 5.20597304,
       0.        , 0.56527709, 0.28263855, 0.30757724, 0.91935175])

In [22]:
bm25.doc_freqs

[{'cat': 1, 'saw': 1, 'the': 1, 'dog': 1},
 {'dog': 1, 'saw': 1, 'the': 1, 'cat': 1},
 {'dog': 3, 'and': 2, 'are': 1, 'more': 1, 'than': 1, 'cat': 1},
 {'cat': 1},
 {'i': 1, 'saw': 1, 'a': 2, 'cat': 1, 'and': 1, 'lion': 1},
 {'lion': 1, 'is': 1, 'the': 1, 'best': 1, 'animal': 1},
 {'cat': 1, 'and': 1, 'dog': 1, 'are': 1, 'animal': 1},
 {'i': 1, 'have': 1, 'the': 1, 'best': 1, 'dog': 1},
 {'lion': 1, 'ate': 1, 'the': 1, 'dog': 1},
 {'cat': 8, 'dog': 8}]

In [31]:
import torch 
a = torch.tensor(2., requires_grad=True)
b = 3
b = b + a

In [8]:
import tiktoken
tok = tiktoken.encoding_for_model("gpt-4")

In [9]:
tok.encode('')

[]

In [36]:
cc.requires_grad

False

In [1]:
from transformers import AutoTokenizer

tok = AutoTokenizer.from_pretrained('gpt2')

In [2]:
dd = tok.encode("i am a bad person", return_tensors='pt')

In [3]:
dd

tensor([[  72,  716,  257, 2089, 1048]])

In [6]:
type(dd)
import torch

In [10]:
voc_size = 5
out = torch.zeros((1,voc_size), dtype=torch.uint8)
out.index_fill(1, torch.tensor([0,3]), 1)

tensor([[1, 0, 0, 1, 0]], dtype=torch.uint8)

In [12]:
a = torch.ones((1,4))
b= torch.zeros((1,4))
torch.cat([a,b]).shape

torch.Size([2, 4])

In [15]:
b/a

tensor([[0., 0., 0., 0.]])

In [ ]:
doc_len = docs.sum(1, keepdim=True).repeat(1,docs.shape[-1]) /avgdl
docs_idf = idf * ((k1 + 1) * docs ) / (docs + k1 *(1 - b + b * doc_len))
scores = queries * docs_idf

In [1]:
from scripts.rankbm25_ml import BM25Tune

In [1]:
import torch
from torch import nn



In [2]:
model = BM25Tune()

In [8]:
list(model.named_parameters())

[('k1',
  Parameter containing:
  tensor(1., device='cuda:0', requires_grad=True)),
 ('b',
  Parameter containing:
  tensor(2., device='cuda:0', requires_grad=True)),
 ('epsilon',
  Parameter containing:
  tensor(0.2000, device='cuda:0', requires_grad=True)),
 ('avgdl_bias',
  Parameter containing:
  tensor(0., device='cuda:0', requires_grad=True)),
 ('idf_bias',
  Parameter containing:
  tensor(0.5000, device='cuda:0', requires_grad=True))]

In [7]:
model.to('cuda:0')

BM25Tune()

In [9]:
from transformers import  AdamW
opt = AdamW(model.parameters(), lr=.001)

/home/ubuntu/miniconda3/envs/recht/lib/python3.12/site-packages/transformers/optimization.py:457: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


In [10]:
torch.save(model.state_dict(), 'output/model.pt')

In [2]:
import torch
mdlft = torch.load('/home/ubuntu/projects/regnlp/output/bm25_idft.pt', weights_only=True)
mdlbs = torch.load('/home/ubuntu/projects/regnlp/output/bm25.pt', weights_only=True)
mdlftrnd = torch.load('/home/ubuntu/projects/regnlp/output/bm25_idft_rnd.pt', weights_only=True)

In [3]:
import pandas as pd 
df = pd.DataFrame({'base':mdlbs['idf'].numpy(), 'ftune':mdlft['idf'].numpy(), 'ftunernd':mdlftrnd['idf'].numpy()})

In [4]:
df.to_csv('results/idf_comp.csv')

In [22]:
abs(df['base'] - df['ftune']).min()

5.53131103515625e-05

In [23]:
mdlbs['k1'].item()

1.5

In [24]:
torch.tensor([1,2,3]).shape

torch.Size([3])

In [ ]:
import json
from sentence_transformers import SentenceTransformer
from sentence_transformers.evaluation import InformationRetrievalEvaluator



def convert2format(queries, corpus):
	new_q, mapping = {}, {}
	new_c = {k:v['txt'] for k,v in corpus.items()}
	for i,q in enumerate(queries):
		new_q[str(i)] = q['query']
		mapping[str(i)] = [str(p) for p in q['pos']]
	return new_c, new_q, mapping




corpus = json.load(open('/home/ubuntu/projects/regnlp/data/ObliQADataset/new/corpus.json'))
queries = json.load(open('/home/ubuntu/projects/regnlp/data/ObliQADataset/new/test.json'))
new_c, new_q, mapping = convert2format(queries, corpus)

model = SentenceTransformer('intfloat/e5-base-v2')
ir_evaluator = InformationRetrievalEvaluator(
	queries=new_q,
	corpus=new_c,
	relevant_docs=mapping,
	show_progress_bar=True
)
results = ir_evaluator(model)
print(results)
